function_words = {u'a', u'algo', u'alguien', u'alguna', u'algunas', u'algunos',
        u'ambos', u'aquel', u'aquella', u'aquellas', u'aquellos', u'aunque',
        u'cada', u'como', u'con', u'cosa', u'cual', u'cuales', u'cualquier',
        u'cualquiera', u'cuando', u'cuanta', u'cuantas', u'cuanto', u'cuantos',
        u'de', u'donde', u'dos', u'el', u'ella', u'ellas', u'ello', u'ellos',
        u'en', u'esa', u'esas', u'ese', u'esos', u'esta', u'estas', u'este',
        u'estos', u'hasta', u'la', u'las', u'le', u'les', u'lo', u'los', u'me',
        u'mi', u'mia', u'mias', u'mio', u'mios', u'mis', u'nadie', u'nos',
        u'nosotras', u'nosotros', u'o', u'para', u'pero', u'por', u'porque',
        u'pues', u'puesto', u'que', u'quien', u'quienes', u'se', u'si', u'sin',
        u'sobre', u'solamente', u'su', u'sus', u'suyo', u'tambien', u'te',
        u'ti', u'todas', u'todo', u'todos', u'tu', u'tus', u'tuyo', u'un',
        u'una', u'unas', u'uno', u'unos', u'usted', u'ustedes', u'y', u'yo',
        u'es', u'ya', u'al', u'del', u'hay', u'esto'}